# Generated by Django 4.0.3 on 2022-03-21 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapriori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='csv',
            field=models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(['csv'])]),
        ),
    ]
